name: ChemXGNN
channels:
  - rdkit
  - pytorch
  - dglteam
  - defaults
dependencies:
  - cudatoolkit=10.1.243
  - dgl-cuda10.1=0.7.0
  - dgllife=0.2.8
  - ipython=7.26.0
  - matplotlib-base=3.3.4
  - matplotlib=3.4.3
  - scipy=1.7.1
  - molvs=0.1.1
  - numpy=1.21.2
  - pandas=1.3.0
  - pip=21.0.1
  - pytorch=1.7.1
  - rdkit=2020.03.1
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - tqdm=4.62.1
  - requests=2.26.0
  - torch-geometric=2.0.3
  - torchvision=0.11.1
  - networkx==2.6.2
  - pgmpy=0.1.11
  - jupyter